language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=py34
    - python: 3.8
      env: TOXENV=py35
    - python: pypy
      env: TOXENV=pypy
    - env: TOXENV=flake8
install:
  - pip install tox
script:
  - tox