# Build config file
# Placed in current working directory of zcbe
[info]
build-name = "name"
prefix = "prefix"
hostname = "i486-linux-gnu"
env = [
["CC", "gcc"],
["CFLAGS", "-W -Wall"],
["LDFLAGS", "-lm"],
["env-name", "env-val"],
]
